MAX_TAG_NAME_LENGTH = 200
MAX_TAG_COLOR_LENGTH = 7
MAX_TAG_SLUG_LENGTH = 200
MAX_INGREDIENT_NAME_LENGTH = 150
MAX_MEASUREMENT_UNIT_LENGTH = 150
MAX_RECIPE_NAME_LENGTH = 200
MIN_VALUE_COOKING_TIME = 1
MIN_VALUE_INGREDIENT_AMOUNT = 1

MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 150
MAX_FIRSTNAME_LENGTH = 150
MAX_LASTNAME_LENGTH = 150
