# Generated by Django 3.2.3 on 2023-10-29 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Укажите цветовой HEX-код', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введенное значение не соответствует формату HEX!', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цветовой HEX-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Укажите уникальный слаг', max_length=200, unique=True, verbose_name='Уникальный слаг'),
        ),
    ]
