# Generated by Django 3.2.3 on 2023-11-01 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, help_text='Укажите название рецепта', max_length=200, validators=[django.core.validators.RegexValidator(message='В названии рецепта можно использовать только буквы, скобки, знаки дефис и кавычки!', regex='^[а-яА-Яa-zA-ZёЁ\\s\\-\\(\\)\\"\\\'«»]+$')], verbose_name='Название рецепта'),
        ),
    ]
