# Generated by Django 3.2.3 on 2023-11-01 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Укажите имя', max_length=150, validators=[django.core.validators.RegexValidator(message='В имени и фамилии можно использовать только буквы и знак дефис!', regex='^[а-яА-Яa-zA-Z\\s\\-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Укажите фамилию', max_length=150, validators=[django.core.validators.RegexValidator(message='В имени и фамилии можно использовать только буквы и знак дефис!', regex='^[а-яА-Яa-zA-Z\\s\\-]+$')], verbose_name='Фамилия'),
        ),
    ]
