# Generated by Django 3.2.3 on 2023-11-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
        ('users', '0002_auto_20231101_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='users_favorite_recipes', to='recipes.Recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart_recipes',
            field=models.ManyToManyField(blank=True, related_name='users_shopping_cart_recipes', to='recipes.Recipe', verbose_name='Рецепты в корзине покупок'),
        ),
    ]
